version: '2'
services:
  hazelcast-jet:
    image: hazelcast/hazelcast-jet
    volumes:
        - ./src/main/resources:/opt/hazelcast-jet/config_ext/
    environment:
        - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast-jet/config_ext/hazelcast.yaml -Dgroup.name=hazelcast-jet-docker-compose
  hazelcast-jet-submit:
    image: hazelcast/hazelcast-jet
    volumes:
        - ./src/main/resources:/opt/hazelcast-jet/config_ext/
        - ./jars/:/jars/
    environment:
        - JAVA_OPTS=-Dhazelcast.client.config=/opt/hazelcast-jet/config_ext/hazelcast-client.yaml -Dhazelcast.member.address=hazelcast-jet -Dgroup.name=hazelcast-jet-docker-compose
        - JOB_JAR=${JOB_JAR}
    depends_on:
        - hazelcast-jet
    container_name: hazelcast-jet-submit
    working_dir: /opt/hazelcast-jet/
    entrypoint: jet -v submit $JOB_JAR

