name: Build latest-snapshot OS and EE image

on:
  workflow_dispatch:
    inputs:
      JET_VERSION:
        description: 'Version of Jet to build the image for'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: 4.2.0-7

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build/Push Slim OSS image
        run: |
          docker buildx build --push \
            --build-arg JET_VERSION=${{ github.event.inputs.JET_VERSION }} \
            --build-arg JET_VARIANT="-slim" \
            --tag hazelcast/hazelcast-jet:latest-snapshot-slim \
            --platform=linux/arm64,linux/amd64 hazelcast-jet-oss

      - name: Build/Push Fat OSS image
          run: |
            docker buildx build --push \
              --build-arg JET_VERSION=${{ github.event.inputs.JET_VERSION }} \
              --tag hazelcast/hazelcast-jet:latest-snapshot \
              --platform=linux/arm64,linux/amd64 hazelcast-jet-oss

      - name: Build/Push Slim EE image
        run: |
          docker buildx build --push \
            --build-arg JET_VERSION=${{ github.event.inputs.JET_VERSION }} \
            --build-arg JET_VARIANT="-slim" \
            --tag hazelcast/hazelcast-jet-enterprise:latest-snapshot-slim \
            --platform=linux/arm64,linux/amd64 hazelcast-jet-enterprise

      - name: Build/Push Fat EE image
          run: |
            docker buildx build --push \
              --build-arg JET_VERSION=${{ github.event.inputs.JET_VERSION }} \
              --tag hazelcast/hazelcast-jet-enterprise:latest-snapshot \
              --platform=linux/arm64,linux/amd64 hazelcast-jet-enterprise
