name: Build OS and EE image

on:
  create:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        type:
          - folder: hazelcast-jet-oss
            image: hazelcast-jet
          - folder: hazelcast-jet-enterprise
            image: hazelcast-jet-enterprise
        variant:
          - name: slim
            suffix: -slim
          - name: full
            suffix: ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Print Release Version
        run: |
          echo ${{ env.RELEASE_VERSION }}

      - name: Check if latest tag should be pushed
        run: echo "PUSH_LATEST=$([[ $(git tag --list "v*" | sort | tail -n 1) = "${GITHUB_REF:10}" ]] && echo yes || echo no)" >> $GITHUB_ENV
      - name: Print Push Latest
        run: |
          echo ${{ env.PUSH_LATEST }}

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: 4.2.0-7

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build/Push ${{ matrix.type }} ${{ matrix.variant.name }}  image
        run: |
          if [[ "${{ env.PUSH_LATEST }}" == "yes" ]]; then
            docker buildx build --push \
              --build-arg JET_VERSION=${{ github.event.inputs.JET_VERSION }} \
              --build-arg JET_VARIANT="${{ matrix.variant.name }}" \
              --tag hazelcast/${{ matrix.type.image }}:${{ env.RELEASE_VERSION }}${{ matrix.variant.suffix }} \
              --tag hazelcast/${{ matrix.type.image }}:latest${{ matrix.variant.suffix }} \
              --platform=linux/arm64,linux/amd64 ${{ matrix.type.folder }}
          else
            docker buildx build --push \
              --build-arg JET_VERSION=${{ github.event.inputs.JET_VERSION }} \
              --build-arg JET_VARIANT="${{ matrix.variant.name }}" \
              --tag hazelcast/${{ matrix.type.image }}:${{ env.RELEASE_VERSION }}${{ matrix.variant.suffix }} \
              --platform=linux/arm64,linux/amd64 ${{ matrix.type.folder }}
          fi
